In [2]:
import torch
import numpy as np

In [5]:
A = torch.arange(5)  # tensor([0, 1, 2, 3, 4])
B = A[1:]          # 对A进行截取获得:tensor([1, 2, 3, 4])
print(A, A.dtype)
print(B, B.dtype)
print(A.storage().data_ptr())
print(B.storage().data_ptr())
print(A[0].storage().data_ptr())
print(B[0].storage().data_ptr())
print(A[0].data_ptr())
print(B[0].data_ptr())
print(A.storage_offset(), B.storage_offset())

print("###########################")
C=A[::2]
print(C)
# print(C.storage())
print(C.is_contiguous())
print(C.stride())
print(A.stride())
print(C.shape)

tensor([0, 1, 2, 3, 4]) torch.int64
tensor([1, 2, 3, 4]) torch.int64
2559443949376
2559443949376
2559443949376
2559443949376
2559443949376
2559443949384
0 1
###########################
tensor([0, 2, 4])
False
(2,)
(1,)
torch.Size([3])


In [380]:
# numpy访问存储区的方法
a = np.arange(5)  # tensor([0, 1, 2, 3, 4])
b = a[2:]         # 对A进行截取获得:tensor([2, 3, 4])

print(id(a))
print(id(b))
print("###########################")
# 访问存储区真实的存储的数据
print(a.__array_interface__['data'][0])
print(b.__array_interface__['data'][0])

1472004404400
1471880567760
###########################
1471971443888
1471971443896


In [8]:
m = [1, 2, 3]
print('m', m, id(m), id(m[0]))
n = m[1:]
print('n   ', n, id(n), id(n[0]))
print(id(m[1]) == id(n[0])) 
# n[0] = 4
# print('m', m, id(m), id(m[0]))
# print('n   ', n, id(n), id(n[0]))

m [1, 2, 3] 2559517717952 140728166588160
n    [2, 3] 2559517717056 140728166588192
True


In [359]:
# 切片时的神奇现象，论证了为什么不能用id()
a = torch.tensor([0,1,2,3])
print(id(a[0]))
print(id(a[0].storage()))
print(a[0].storage().data_ptr())
print("###########################")

print(id(a[0]))
print(id(a[0].storage()))
print(a[0].storage().data_ptr())
print("###########################")

print(id(a[0]))
print(id(a[0].storage()))
print(a[0].storage().data_ptr())



# print(id(a[0])==id(a[0])) #先创建左侧，获取到左侧ID，然后销毁左侧ID；再创建右侧，获取右侧ID，再销毁右侧ID
# 不可使用下面的语句，卡了python的id设定的bug
# print(id(a[0]) is id(a[0])) #同时创建左右两侧ID，则ID必不可能相同。


1472003733760
1472006607936
1471976496384
###########################
1472043755296
1472006586624
1471976496384
###########################
1472043753616
1472006673728
1471976496384


In [385]:
# 知乎上的一个有意思的提问
t0 = torch.tensor([1, 2, 3])
print(id(t0.storage())) # 2028947247624
t1 = t0.view(1, 3)
print(id(t0.storage())) # 2028947289032
print(id(t1.storage())) # 2028947247624
print(id(t0.storage())==id(t1.storage()))# True

1472006088064
1472003145344
1472003143744
True


#### 两个例子，表明了tensor和list对象的差异性

In [19]:
a = torch.tensor([[1,2],[3,4]])
print(id(a), id(a[0]), id(a[1]))
a[1:] = torch.tensor([0, 0])
print(id(a), id(a[0]), id(a[1])) # 2257492943160 2257492943320 2257492943320 ←①
a0 = a[0]
print(id(a0)) # 2257492943320
a1 = a[1]
print(id(a1)) # 2257492943400 ←②

2559519448736 2559518210864 2559518210864
2559519448736 2559517715328 2559517715328
2559517715328
2559519537488


In [18]:
a = [[1,2],[3,4]]
print(id(a), id(a[0]), id(a[1])) # 2559517439872 2559383846848 2559517746368
a[1:] = [[0, 0]] 
print(a) # [[1, 2], [0, 0]]
print(id(a), id(a[0]), id(a[1])) # 2559517439872 2559383846848 2559517718720

a0 = a[0]
print(id(a0)) # 2559383846848
a1 = a[1]
print(id(a1)) # 2559517718720

2559517439872 2559383846848 2559517746368
[[1, 2], [0, 0]]
2559517439872 2559383846848 2559517718720
2559383846848
2559517718720


In [32]:
a = torch.tensor(1)
print(a,a.dtype,a.storage().data_ptr())

print(a.storage_offset())
a-=1
# a=a-1
# print(a.storage_offset(),b.storage_offset())
print(a.storage_offset())
print(a,a.dtype,a.storage().data_ptr())
# print(b,b.dtype,b.storage().data_ptr())

tensor(1) torch.int64 2559445325760
0
0
tensor(0) torch.int64 2559445325760


In [37]:
a = torch.ones((2,3,3,3))
print(a)

a-=1
a/=2
print(a)
print(a.shape)

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])
tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]])
torch.Size([2, 3, 3, 3])
