In [3]:
import numpy as np
import torch


In [4]:
print("############## 原始数据类型 ##############")
a = torch.randn(2, 2)  # 默认类型，Initially dtype=float32, device=cpu
print(a)
print(a.dtype)

############## 原始数据类型 ##############
tensor([[-0.5533,  1.0843],
        [-0.5891, -0.2935]])
torch.float32


In [5]:
print("############## 使用tensor.to 转换后 ##############")
b=a.to(torch.float64)
print(b)
print(b.dtype)

############## 使用tensor.to 转换后 ##############
tensor([[-0.5533,  1.0843],
        [-0.5891, -0.2935]], dtype=torch.float64)
torch.float64


In [27]:
print("############## 使用tensor.to 转换，但保持原样数据类型，从而验证参数copy的作用 ##############")
c=a.to(torch.float32)
print(hex(id(a)))
print(hex(id(c)))
print(hex(id(a[0][0])))
print(hex(id(c[0][0])))
print(c)
print(a.dtype)
print(c.dtype)

############## 使用tensor.to 转换，但保持原样数据类型，从而验证参数copy的作用 ##############
0x24629323c70
0x24629323c70
0x24629323590
0x24629323590
tensor([[ 0.6689, -0.9043],
        [ 1.1141, -0.2554]])
torch.float32
torch.float32


In [28]:
print("############## 对照组，当 copy=True时的输出效果 ##############")
d=a.to(torch.float32, copy=True)
print(hex(id(a)))
print(hex(id(d)))
print(hex(id(a[0][0])))
print(hex(id(d[0][0])))
print(c)
print(a.dtype)
print(d.dtype)

############## 对照组，当 copy=True时的输出效果 ##############
0x24629323c70
0x2462932c590
0x2462932c450
0x2462932c220
tensor([[ 0.6689, -0.9043],
        [ 1.1141, -0.2554]])
torch.float32
torch.float32


In [29]:
print("############## 验证深复制 ##############")
b[0][0]=999.5
print(b)
print(b.dtype)
print(hex(id(b)))
print(a)
print(a.dtype)
print(hex(id(a)))



############## 验证深复制 ##############
tensor([[ 9.9950e+02, -9.0432e-01],
        [ 1.1141e+00, -2.5539e-01]], dtype=torch.float64)
torch.float64
0x24629323b30
tensor([[ 0.6689, -0.9043],
        [ 1.1141, -0.2554]])
torch.float32
0x24629323c70


In [32]:
cuda0 = torch.device('cuda:0')
a2 = torch.randn(2, 2)
print(a2)
print(a2.dtype)
print(hex(id(a2)))
b2 = a2.to(cuda0)
print(b2)
print(b2.dtype)
print(hex(id(b2)))

c2 = b2.to(cuda0, dtype=torch.float64)
print(c2)
print(c2.dtype)
print(hex(id(c2)))


tensor([[-0.5810, -0.2508],
        [ 0.6758,  0.4693]])
torch.float32
0x246061fdc70
tensor([[-0.5810, -0.2508],
        [ 0.6758,  0.4693]], device='cuda:0')
torch.float32
0x2460621d400
tensor([[-0.5810, -0.2508],
        [ 0.6758,  0.4693]], device='cuda:0', dtype=torch.float64)
torch.float64
0x246065a70e0


In [46]:
a3 = torch.randn(2,1)
other = torch.randn((3,4), dtype=torch.half, device='cuda:0')
print(a3)
print(a3.dtype)
print(hex(id(a3)))
print(other)
print(other.dtype)
print(hex(id(other)))

b3=a3.to(other)
print(b3)
print(b3.dtype)
print(hex(id(b3)))

tensor([[-1.4872],
        [-1.9471]])
torch.float32
0x2465c7670e0
tensor([[ 0.6177,  1.3418, -0.5405, -1.5771],
        [ 0.6143, -1.0752,  0.1556,  0.7422],
        [-1.2363,  0.9189, -0.6006, -1.0938]], device='cuda:0',
       dtype=torch.float16)
torch.float16
0x2460621e450
tensor([[-1.4873],
        [-1.9473]], device='cuda:0', dtype=torch.float16)
torch.float16
0x24651d02180
