In [2]:
import torch

In [4]:
a = torch.randn(2,3) #定义一个标准正态分布（均值为0，方差为1）的随机数张量
b = 6
print(a)
print(torch.is_tensor(a))
print(torch.is_tensor(b))


tensor([[-1.9224,  1.7443,  0.3528],
        [ 0.6287, -0.7736, -0.1793]])
True
False


In [3]:
# torch.is_storage()
a = torch.rand(2,3) #定义一个在区间[0,1]的均匀分布随机数的张量
b = torch.FloatStorage([1,2,3,4,5,6]) #还有ByteStorage,ShortStorage,IntStorage,LongStorage,DoubleStorage
print(a)
print(a.storage())
print(torch.is_storage(a))
print(torch.is_storage(b))


tensor([[0.6989, 0.5152, 0.7836],
        [0.8475, 0.9963, 0.1555]])
 0.6989085674285889
 0.5152345299720764
 0.7835797071456909
 0.8474761247634888
 0.9963153004646301
 0.155498206615448
[torch.FloatStorage of size 6]
False
True


In [5]:
# torch.is_complex()
a = torch.tensor([2, 4], dtype = torch.float32)
b = torch.tensor([3, 6], dtype = torch.float32)
c = torch.complex(a, b)
print(c) # tensor([2.+3.j, 4.+6.j])
print(torch.is_complex(c)) # True

tensor([2.+3.j, 4.+6.j])
True


In [6]:
a = torch.tensor([3, 6], dtype = torch.float64)
print(a)# tensor([3., 6.], dtype=torch.float64)
print(torch.is_floating_point(a)) # True


tensor([3., 6.], dtype=torch.float64)
True


#### 设置dtype

In [2]:
# 如不设置，则输出默认类型，
print(torch.tensor([False]).dtype)
print(torch.tensor([1, 3]).dtype)
print(torch.tensor([1.2, 3]).dtype)
print(torch.tensor([1.2, 3j]).dtype)
# output：
# torch.bool
# torch.int64
# torch.float32
# torch.complex64

# 设置后再次输出
torch.set_default_dtype(torch.float64)
print(torch.tensor([False]).dtype)
print(torch.tensor([1, 3]).dtype)
print(torch.tensor([1.2, 3]).dtype)
print(torch.tensor([1.2, 3j]).dtype)

# output：
# torch.bool
# torch.int64
# torch.float64
# torch.complex128

torch.bool
torch.int64
torch.float32
torch.complex64
torch.bool
torch.int64
torch.float64
torch.complex128


In [3]:
print(torch.get_default_dtype()) # torch.float64
torch.set_default_tensor_type(torch.FloatTensor)
print(torch.get_default_dtype()) # torch.float32

torch.float64
torch.float32


打印设置

In [9]:
torch.set_printoptions(precision=2)
print(torch.tensor([1.12345]))
torch.set_printoptions(threshold=10)
print(torch.arange(10))

tensor([1.12])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [4]:
a = torch.randn(1, 7)
print(a) 
# tensor([[ 1.9613, -0.8069,  0.6356, -0.4459,  0.0860, -0.7173, -1.2878]])
torch.set_printoptions(precision = 6, threshold=6, edgeitems=1,linewidth=20 )
print(a) 
# tensor([[-0.326266,
#           ...,
#          -0.461118]])

tensor([[-0.326266,  ..., -0.461118]])
tensor([[-0.326266,
          ...,
         -0.461118]])


In [2]:
import torch
a = torch.randn(1, 3)
print(a) 
# tensor([[ 1.7177,  0.7020, -0.6267,  0.9570, -1.1070]])
torch.set_printoptions(profile='short', sci_mode =True)
print(a) 
# tensor([[1.72e+00, 7.02e-01, -6.27e-01, 9.57e-01, -1.11e+00]])

tensor([[ 1.7177,  0.7020, -0.6267,  0.9570, -1.1070]])
tensor([[1.72e+00, 7.02e-01, -6.27e-01, 9.57e-01, -1.11e+00]])


In [5]:
input = torch.tensor([-1.5, 0, 2.0])
values = torch.tensor([-1.5])
print(torch.heaviside(input, values))
values = torch.tensor([1.2, -2.0, 3.5])
print(torch.heaviside(input, values))


tensor([ 0.0000, -1.5000,  1.0000])
tensor([ 0., -2.,  1.])
